g = 0;
printl("global env: g = ${g}");

{
    o = 10;
    printl("outer env: g = ${g}, o = ${o}");

    g++;
    printl("changed value of g");
    printl("outer env: g = ${g}, o = ${o}");

    {
        i = 100;
        printl("inside env: g = ${g}, i = ${i}");

        g++;
        o++; ???
        i++;

        printl("changed values of g, i");
        printl("inside env: g = ${g}, i = ${i}");
    }
    printl("outer env: g = ${g}, o = ${o}");
}

printl("global env: g = ${g}");
