import("lib/stdtypes.jj");

hanoi = { (n, t_1, t_3, t_2)
    if n == 1 {
        printl("Move disk 1 from ${t_1} to ${t_3}");
        return();
    }
    hanoi(n - 1, t_1, t_2, t_3);
    printl("Move disk ${n} from ${t_1} to ${t_3}");
    hanoi(n - 1, t_2, t_3, t_1);
}

num = input("Enter the number of disks: ");
num = eval(num + ";");

if (is_num(num)) {
    hanoi(num, "A", "C", "B");
} else {
    printl("INVALID INPUT!");
}

